### ISSUE TITLE
Running via 'node config.js' gives EventEmitter memory leak warning

### ISSUE THREAD

**Issue by ghost** [jimmyhillis/slack-irc-plugin#6]
Running on Ubuntu 14.04 with latest version of node, gives me the following warning:

root@server:~/slack-irc-plugin# node config-example.js
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Client.addListener (events.js:160:15)
    at Client.whois (/root/slack-irc-plugin/node_modules/irc/lib/irc.js:854:14)
    at /root/slack-irc-plugin/lib/bot.js:56:25
    at Array.forEach (native)
    at Client.<anonymous> (/root/slack-irc-plugin/lib/bot.js:55:28)
    at Client.emit (events.js:98:17)
    at Client.<anonymous> (/root/slack-irc-plugin/node_modules/irc/lib/irc.js:320:26)
    at Client.emit (events.js:95:17)
    at /root/slack-irc-plugin/node_modules/irc/lib/irc.js:669:22
    at Array.forEach (native)

**Comment by morenoh149** [comment]
I get this as well.

**Comment by ChihHaoTW** [comment]
me too

**Comment by Pwn9** [comment]
i am getting this also:

 (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.

Trace
    at Client.addListener (events.js:160:15)
    at Client.whois (/home/pwn9/node_projects/slack-irc-plugin/node_modules/irc/lib/irc.js:984:14)
    at /home/pwn9/node_projects/slack-irc-plugin/lib/bot.js:75:25
    at Array.forEach (native)
    at Client.<anonymous> (/home/pwn9/node_projects/slack-irc-plugin/lib/bot.js:74:28)
    at Client.emit (events.js:98:17)
    at Client.<anonymous> (/home/pwn9/node_projects/slack-irc-plugin/node_modules/irc/lib/irc.js:358:26)
    at Client.emit (events.js:95:17)
    at iterator (/home/pwn9/node_projects/slack-irc-plugin/node_modules/irc/lib/irc.js:756:22)
    at Array.forEach (native)

**Comment by asadpakistani** [comment]
Any luck on this issue, very annoying.
